# G4CMP/quasiparticle/GNUmakefile -- for building phonon propagation demo
# $Id$
#
# 20160518  Use G4CMPINSTALL instead of ".." to find includes

G4CMP_NAME := g4cmpQuasiparticle
include $(G4CMPINSTALL)/g4cmp.gmk
