/run/initialize
/process/setVerbose 1 G4CMPeDriftBoundary
/process/setVerbose 1 G4CMPhDriftBoundary
/tracking/verbose 1
/gun/number 5

/vis/open OGLIX 800x800-0+0
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointVector 0 1 -0.1
/vis/viewer/zoomTo 1.2
/vis/drawVolume
/vis/scene/add/trajectories
/vis/ogl/set/printFilename testRefl
/vis/ogl/set/printMode pixmap
/vis/ogl/printEPS

/run/beamOn 1
