#-------------------------------------
# Validation_PolycrystalElasticScattering.mac
# linehan3@fnal.gov
# 07/27/2025
#
# Validation of phonon polycrystalline scattering

#-------------------------------------
# Geometry Customs Go First
# Set geometry ID
/g4cmp/GeometryID 1
/g4cmp/StepFile Validation_PolycrystalElasticScattering.txt

#-------------------------------------
# Initialize the run
/run/initialize

#-------------------------------------
# Set up the viewer
/vis/open OGL
/vis/viewer/set/upVector 0 1 0
/vis/viewer/set/viewpointThetaPhi 30 150
/vis/viewer/zoom 1.4
/vis/drawVolume

#-------------------------------------
# Turn off all new processes
/process/inactivate phononScattering
/process/inactivate phononDownconversion
#/process/inactivate phononPolycrystalElasticScattering
/process/inactivate qpRecombination
/process/inactivate qpRadiatesPhonon
/process/inactivate scPairBreaking
/process/inactivate qpDiffusion
/process/inactivate qpLocalTrapping
/process/inactivate qpDiffusionTimeStepper

#-------------------------------------
# For printing progress and tracks
/run/printProgress 1
/tracking/verbose 0
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories

#-------------------------------------
# Set number of phonon bounces
/g4cmp/phononBounces 10

#-------------------------------------
# Generate 1 phonon per event, in a tiny parallelepiped volume
/gps/number 1
/gps/particle phononTF
/gps/pos/type Point


#-------------------------------------
# Set the position. 
#/gps/pos/centre 0.0 0.0 0.0 mm # Center of Si
#/gps/pos/centre 0.0 0.0 -1.0 mm # Center of Ge
/gps/pos/centre 0.0 0.0 -1.500050 mm # Center of Al1
#/gps/pos/center 0.0 0.0 -1.55 mm # Near-Center of Al2
#/gps/pos/center 0.0 0.0 -1.65 mm # Near-Center of Nb for Al3

#-------------------------------------
# Set the angular distribution. 
# For Phonon sims
/gps/ang/type iso
/gps/ene/type Mono
/gps/energy 0.0040 eV
/run/beamOn 1000
