# G4CMP/validation/GNUmakefile -- for building phonon propagation demo
# $Id$
#
# 20160518  Use G4CMPINSTALL instead of ".." to find includes

G4CMP_NAME := g4cmpValidation
include $(G4CMPINSTALL)/g4cmp.gmk
