#-------------------------------------
# Now initialize the run
/run/initialize

/vis/open OGL
/vis/viewer/set/upVector 0 1 0
/vis/viewer/set/viewpointThetaPhi 90 180
/vis/viewer/zoom 1.4
/vis/drawVolume

/g4cmp/phononBounces 0
/g4cmp/bogoliubovQPBounces 5000
/g4cmp/verbose 0

/process/inactivate phononScattering
/process/inactivate phononDownconversion
/process/inactivate phononPolycrystalElasticScattering
/process/inactivate qpRecombination
/process/inactivate qpRadiatesPhonon
/process/inactivate scPairBreaking
#/process/inactivate qpDiffusion
#/process/inactivate qpLocalTrapping
/process/inactivate qpDiffusionTimeStepper

/run/printProgress 1

# for drawing the tracks
# (if too many tracks cause core dump => storeTrajectory 0)
/tracking/verbose 0
/tracking/storeTrajectory 1
/vis/scene/endOfEventAction accumulate
/vis/scene/add/trajectories

#/g4cmp/phononBounces 0
#/g4cmp/bogoliubovQPBounces 5000
#/g4cmp/verbose 6

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set phononTS Red 
/vis/modeling/trajectories/drawByParticleID-0/set phononTF Green
/vis/modeling/trajectories/drawByParticleID-0/set phononL Blue
/vis/modeling/trajectories/drawByParticleID-0/set BogoliubovQP White

# Generate 1 QP per event. Place in the aluminum block
/gps/number 1
/gps/particle BogoliubovQP
/gps/pos/type Volume
/gps/pos/shape Para
/gps/pos/centre 0 37.2 16.7 mm
#/gps/pos/centre 19.0 19.0 16.7 mm

#These XY values must be just under half of the values used for the chip dimensions above Defaults
/gps/pos/halfx 0.0001 mm
/gps/pos/halfy 0.0001 mm
/gps/pos/halfz 0.0001 mm

/gps/ang/type iso
/gps/ang/mintheta 89.99999999 deg
/gps/ang/maxtheta 90.00000001 deg
/gps/ene/type Mono
/gps/energy 0.001 eV
/run/beamOn 10000
