# G4CMP/phonon/GNUmakefile -- for building phonon propagation demo
# $Id: bb6e2ce10a89515fa367d15dcff13f8b03e7a4c3 $
#
# 20160518  Use G4CMPINSTALL instead of ".." to find includes

G4CMP_NAME := g4cmpKVtables
include $(G4CMPINSTALL)/g4cmp.gmk
